server {
    listen       80;
    listen  [::]:80;
    # Change this to your Azure DNS name
    server_name  alertkisan.centralindia.cloudapp.azure.com;
    # server_name localhost;

    # location / {
    #     root   /usr/share/nginx/html;
    #     index  index.html index.htm;
    # }
    location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            # Add this to ensure Nginx doesn't try to be fancy
            try_files $uri =404;
    }
    location / {
        # Use the service name from docker-compose
        proxy_pass http://mandi-app:8080; 
        
        # Standard Proxy Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # This tells Spring Boot if the original request was HTTP or HTTPS
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
# server {
#     listen 443 ssl;
#     listen [::]:443 ssl;
#     server_name alertkisan.centralindia.cloudapp.azure.com;

#     # SSL Paths (Certbot will put files here)
#     ssl_certificate /etc/letsencrypt/live/alertkisan.centralindia.cloudapp.azure.com/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/alertkisan.centralindia.cloudapp.azure.com/privkey.pem;

#     location / {
#         proxy_pass http://mandi-app:8080;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme; # Tells Spring Boot the request is HTTPS
#     }
# }