spring.application.name=alertkisan
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=root123

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# API Key
mandi.api.key=579b464db66ec23bdd000001f0640310d2a040ce6de92368dddb2e8f
mandi.api.url=https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=
mandi.api.url_historical=https://api.data.gov.in/resource/35985678-0d79-46b4-9ed6-6f13308a1d24?api-key=
mandi.api.format=json
mandi.api.limit=1000

logging.level.root=ERROR
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
